const msgConstant = {

    //file error
    fileExtensionError: 'File with jpg,png,jpeg,mkv,avi,mp4 extensions are allowed.',

    //user messages
    signUpSuccessful: 'Signup successfully.',
    signUpError: 'Signup not completed.',
    loginSuccessfully: 'Login successfully',
    enterRegisterMobile: 'Please enter register mobile number.',
    userRegister: 'Registration successfully.',
    passwordWrong: 'Password does not match.',
    mobileAlreadyExist: 'Mobile number already registered.',
    userNotRegister: 'Please enter register number.',
    enterEmail: 'Please enter mail.',
    linkExpire: 'Link has expired.',
    forgotMail: 'Forgot mail sent on your register email address.',
    emailAlreadyExist: 'Email already registered.',
    numberAlreadyExist: 'Mobile number already registered.',
    otpSentSucessfully: 'OTP sent successfully.',
    otpNotMatch: 'OTP does not match.',
    profileUpdated: 'Profile updated successfully.',
    otpNotSent: 'OTP not send.',
    usersFetchedSuccessfully: 'User fetch successfully.',
    usersNotFetch: 'User not fetch.',
    selectImage: 'Please select image to upload profile.',
    imageUpdatedSuccessfully: 'Profile image updated successfully.',
    imageNotUpdated: 'Profile image not updated.',
    userNotUpdated: 'User not updated.',
    userUpdatedSuccessfully: 'Profile details updated.',
    userNotFound: 'User not found.',
    passUserIdInBody: 'Please pass "userId" in body.',
    userActivatedSuccessfully: 'User activated successfully.',
    userDeactivatedSuccessfully: 'User deactivated successfully.',
    dashboard: 'Dashboard data fetched successsfully.',
    userCreatedSuccessfully: 'User created successfully.',
    userNotCreated: 'User not created.',
    wrongReferenceCode: 'Your enter reference code does not exist.',
    enterUserId: 'Please enter user Id.',
    enterCorrectUserId: 'Please enter correct user ID.',
    enterName: 'Please enter name.',
    enterMobileNumber: 'Please enter mobile number.',
    enterCountryCode: 'Please enter country code.',
    enterMobileOtp: 'Please enter mobile number and otp.',
    enterOtp: 'Please enter otp.',
    phoneNumberIsNumeric: 'Enter only numeric value for mobile number.',
    phoneNumberUpdated: 'Mobile number updated successfully.',
    phoneNumberNotUpdated: 'Mobile number not updated.',
    passwordSet: 'Password set sccessfully.',
    enterValidMail: 'Please enter valid email address',
    passwordUpdated: 'Password updated successfully.',
    enterEmpId: 'Please enter registered employee Id.',
    enterCorrectPassword: 'Please enter correct password.',
    authorizationError: 'You are not authorized to perform this task.',
    loginOnAnotherDevice: 'Your account is logged in another device.',
    userDelete: 'User deleted successfully.',
    userNotDelete: 'User not deleted successfully.',
    blockByAdmin: 'Your account is blocked by admin.',
    loginUserNotFound: 'Please login again, user not found',
    authorizationTokenRequired: 'Authorization token is required.',
    mobileNotVerified: 'Please verify your mobile number.',
    ratingDone: 'Your rating saved successfully.',
    ratingUpdate: 'Your rating updated successfully.',
    onlyAstrologer: 'You can give rating to only astrologers.',
    accountBlock: 'This account has been blocked by admin.',
    enterCategory: 'Please enter category.',
    categoryAlready: 'Category is already exist.',
    categoryAdded: 'Category added successfully.',
    categoryFetch: 'Category fetch successfully.',
    categoryUpdate: 'Category updated successfully.',
    categoryDelete: 'Category deleted successfully.',
    categoryNotFound: 'Category not found.',
    mailNotSent: 'Email not sent. Try again.',
    categorySelected: 'This category is already selected by astrologer, you can not delete them.'
}

export default msgConstant;